# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/geopros/NetBeansProjects/Project-OSRM-develop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/geopros/NetBeansProjects/Project-OSRM-develop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geopros/NetBeansProjects/Project-OSRM-develop/CMakeFiles /home/geopros/NetBeansProjects/Project-OSRM-develop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geopros/NetBeansProjects/Project-OSRM-develop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named COORDLIB

# Build rule for target.
COORDLIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 COORDLIB
.PHONY : COORDLIB

# fast build rule for target.
COORDLIB/fast:
	$(MAKE) -f CMakeFiles/COORDLIB.dir/build.make CMakeFiles/COORDLIB.dir/build
.PHONY : COORDLIB/fast

#=============================================================================
# Target rules for targets named GITDESCRIPTION

# Build rule for target.
GITDESCRIPTION: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GITDESCRIPTION
.PHONY : GITDESCRIPTION

# fast build rule for target.
GITDESCRIPTION/fast:
	$(MAKE) -f CMakeFiles/GITDESCRIPTION.dir/build.make CMakeFiles/GITDESCRIPTION.dir/build
.PHONY : GITDESCRIPTION/fast

#=============================================================================
# Target rules for targets named OSRM

# Build rule for target.
OSRM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OSRM
.PHONY : OSRM

# fast build rule for target.
OSRM/fast:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/build
.PHONY : OSRM/fast

#=============================================================================
# Target rules for targets named UUID

# Build rule for target.
UUID: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UUID
.PHONY : UUID

# fast build rule for target.
UUID/fast:
	$(MAKE) -f CMakeFiles/UUID.dir/build.make CMakeFiles/UUID.dir/build
.PHONY : UUID/fast

#=============================================================================
# Target rules for targets named UUIDConfigure

# Build rule for target.
UUIDConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UUIDConfigure
.PHONY : UUIDConfigure

# fast build rule for target.
UUIDConfigure/fast:
	$(MAKE) -f CMakeFiles/UUIDConfigure.dir/build.make CMakeFiles/UUIDConfigure.dir/build
.PHONY : UUIDConfigure/fast

#=============================================================================
# Target rules for targets named osrm-datastore

# Build rule for target.
osrm-datastore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osrm-datastore
.PHONY : osrm-datastore

# fast build rule for target.
osrm-datastore/fast:
	$(MAKE) -f CMakeFiles/osrm-datastore.dir/build.make CMakeFiles/osrm-datastore.dir/build
.PHONY : osrm-datastore/fast

#=============================================================================
# Target rules for targets named osrm-extract

# Build rule for target.
osrm-extract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osrm-extract
.PHONY : osrm-extract

# fast build rule for target.
osrm-extract/fast:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/build
.PHONY : osrm-extract/fast

#=============================================================================
# Target rules for targets named osrm-prepare

# Build rule for target.
osrm-prepare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osrm-prepare
.PHONY : osrm-prepare

# fast build rule for target.
osrm-prepare/fast:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/build
.PHONY : osrm-prepare/fast

#=============================================================================
# Target rules for targets named osrm-routed

# Build rule for target.
osrm-routed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osrm-routed
.PHONY : osrm-routed

# fast build rule for target.
osrm-routed/fast:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/build
.PHONY : osrm-routed/fast

Algorithms/DouglasPeucker.o: Algorithms/DouglasPeucker.cpp.o
.PHONY : Algorithms/DouglasPeucker.o

# target to build an object file
Algorithms/DouglasPeucker.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/DouglasPeucker.cpp.o
.PHONY : Algorithms/DouglasPeucker.cpp.o

Algorithms/DouglasPeucker.i: Algorithms/DouglasPeucker.cpp.i
.PHONY : Algorithms/DouglasPeucker.i

# target to preprocess a source file
Algorithms/DouglasPeucker.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/DouglasPeucker.cpp.i
.PHONY : Algorithms/DouglasPeucker.cpp.i

Algorithms/DouglasPeucker.s: Algorithms/DouglasPeucker.cpp.s
.PHONY : Algorithms/DouglasPeucker.s

# target to generate assembly for a file
Algorithms/DouglasPeucker.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/DouglasPeucker.cpp.s
.PHONY : Algorithms/DouglasPeucker.cpp.s

Algorithms/PolylineCompressor.o: Algorithms/PolylineCompressor.cpp.o
.PHONY : Algorithms/PolylineCompressor.o

# target to build an object file
Algorithms/PolylineCompressor.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/PolylineCompressor.cpp.o
.PHONY : Algorithms/PolylineCompressor.cpp.o

Algorithms/PolylineCompressor.i: Algorithms/PolylineCompressor.cpp.i
.PHONY : Algorithms/PolylineCompressor.i

# target to preprocess a source file
Algorithms/PolylineCompressor.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/PolylineCompressor.cpp.i
.PHONY : Algorithms/PolylineCompressor.cpp.i

Algorithms/PolylineCompressor.s: Algorithms/PolylineCompressor.cpp.s
.PHONY : Algorithms/PolylineCompressor.s

# target to generate assembly for a file
Algorithms/PolylineCompressor.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Algorithms/PolylineCompressor.cpp.s
.PHONY : Algorithms/PolylineCompressor.cpp.s

Contractor/EdgeBasedGraphFactory.o: Contractor/EdgeBasedGraphFactory.cpp.o
.PHONY : Contractor/EdgeBasedGraphFactory.o

# target to build an object file
Contractor/EdgeBasedGraphFactory.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/EdgeBasedGraphFactory.cpp.o
.PHONY : Contractor/EdgeBasedGraphFactory.cpp.o

Contractor/EdgeBasedGraphFactory.i: Contractor/EdgeBasedGraphFactory.cpp.i
.PHONY : Contractor/EdgeBasedGraphFactory.i

# target to preprocess a source file
Contractor/EdgeBasedGraphFactory.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/EdgeBasedGraphFactory.cpp.i
.PHONY : Contractor/EdgeBasedGraphFactory.cpp.i

Contractor/EdgeBasedGraphFactory.s: Contractor/EdgeBasedGraphFactory.cpp.s
.PHONY : Contractor/EdgeBasedGraphFactory.s

# target to generate assembly for a file
Contractor/EdgeBasedGraphFactory.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/EdgeBasedGraphFactory.cpp.s
.PHONY : Contractor/EdgeBasedGraphFactory.cpp.s

Contractor/GeometryCompressor.o: Contractor/GeometryCompressor.cpp.o
.PHONY : Contractor/GeometryCompressor.o

# target to build an object file
Contractor/GeometryCompressor.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/GeometryCompressor.cpp.o
.PHONY : Contractor/GeometryCompressor.cpp.o

Contractor/GeometryCompressor.i: Contractor/GeometryCompressor.cpp.i
.PHONY : Contractor/GeometryCompressor.i

# target to preprocess a source file
Contractor/GeometryCompressor.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/GeometryCompressor.cpp.i
.PHONY : Contractor/GeometryCompressor.cpp.i

Contractor/GeometryCompressor.s: Contractor/GeometryCompressor.cpp.s
.PHONY : Contractor/GeometryCompressor.s

# target to generate assembly for a file
Contractor/GeometryCompressor.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/GeometryCompressor.cpp.s
.PHONY : Contractor/GeometryCompressor.cpp.s

Contractor/TemporaryStorage.o: Contractor/TemporaryStorage.cpp.o
.PHONY : Contractor/TemporaryStorage.o

# target to build an object file
Contractor/TemporaryStorage.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/TemporaryStorage.cpp.o
.PHONY : Contractor/TemporaryStorage.cpp.o

Contractor/TemporaryStorage.i: Contractor/TemporaryStorage.cpp.i
.PHONY : Contractor/TemporaryStorage.i

# target to preprocess a source file
Contractor/TemporaryStorage.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/TemporaryStorage.cpp.i
.PHONY : Contractor/TemporaryStorage.cpp.i

Contractor/TemporaryStorage.s: Contractor/TemporaryStorage.cpp.s
.PHONY : Contractor/TemporaryStorage.s

# target to generate assembly for a file
Contractor/TemporaryStorage.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/Contractor/TemporaryStorage.cpp.s
.PHONY : Contractor/TemporaryStorage.cpp.s

DataStructures/Coordinate.o: DataStructures/Coordinate.cpp.o
.PHONY : DataStructures/Coordinate.o

# target to build an object file
DataStructures/Coordinate.cpp.o:
	$(MAKE) -f CMakeFiles/COORDLIB.dir/build.make CMakeFiles/COORDLIB.dir/DataStructures/Coordinate.cpp.o
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/Coordinate.cpp.o
.PHONY : DataStructures/Coordinate.cpp.o

DataStructures/Coordinate.i: DataStructures/Coordinate.cpp.i
.PHONY : DataStructures/Coordinate.i

# target to preprocess a source file
DataStructures/Coordinate.cpp.i:
	$(MAKE) -f CMakeFiles/COORDLIB.dir/build.make CMakeFiles/COORDLIB.dir/DataStructures/Coordinate.cpp.i
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/Coordinate.cpp.i
.PHONY : DataStructures/Coordinate.cpp.i

DataStructures/Coordinate.s: DataStructures/Coordinate.cpp.s
.PHONY : DataStructures/Coordinate.s

# target to generate assembly for a file
DataStructures/Coordinate.cpp.s:
	$(MAKE) -f CMakeFiles/COORDLIB.dir/build.make CMakeFiles/COORDLIB.dir/DataStructures/Coordinate.cpp.s
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/Coordinate.cpp.s
.PHONY : DataStructures/Coordinate.cpp.s

DataStructures/HilbertValue.o: DataStructures/HilbertValue.cpp.o
.PHONY : DataStructures/HilbertValue.o

# target to build an object file
DataStructures/HilbertValue.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/HilbertValue.cpp.o
.PHONY : DataStructures/HilbertValue.cpp.o

DataStructures/HilbertValue.i: DataStructures/HilbertValue.cpp.i
.PHONY : DataStructures/HilbertValue.i

# target to preprocess a source file
DataStructures/HilbertValue.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/HilbertValue.cpp.i
.PHONY : DataStructures/HilbertValue.cpp.i

DataStructures/HilbertValue.s: DataStructures/HilbertValue.cpp.s
.PHONY : DataStructures/HilbertValue.s

# target to generate assembly for a file
DataStructures/HilbertValue.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/HilbertValue.cpp.s
.PHONY : DataStructures/HilbertValue.cpp.s

DataStructures/RestrictionMap.o: DataStructures/RestrictionMap.cpp.o
.PHONY : DataStructures/RestrictionMap.o

# target to build an object file
DataStructures/RestrictionMap.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/RestrictionMap.cpp.o
.PHONY : DataStructures/RestrictionMap.cpp.o

DataStructures/RestrictionMap.i: DataStructures/RestrictionMap.cpp.i
.PHONY : DataStructures/RestrictionMap.i

# target to preprocess a source file
DataStructures/RestrictionMap.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/RestrictionMap.cpp.i
.PHONY : DataStructures/RestrictionMap.cpp.i

DataStructures/RestrictionMap.s: DataStructures/RestrictionMap.cpp.s
.PHONY : DataStructures/RestrictionMap.s

# target to generate assembly for a file
DataStructures/RestrictionMap.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/DataStructures/RestrictionMap.cpp.s
.PHONY : DataStructures/RestrictionMap.cpp.s

DataStructures/RouteParameters.o: DataStructures/RouteParameters.cpp.o
.PHONY : DataStructures/RouteParameters.o

# target to build an object file
DataStructures/RouteParameters.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/RouteParameters.cpp.o
.PHONY : DataStructures/RouteParameters.cpp.o

DataStructures/RouteParameters.i: DataStructures/RouteParameters.cpp.i
.PHONY : DataStructures/RouteParameters.i

# target to preprocess a source file
DataStructures/RouteParameters.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/RouteParameters.cpp.i
.PHONY : DataStructures/RouteParameters.cpp.i

DataStructures/RouteParameters.s: DataStructures/RouteParameters.cpp.s
.PHONY : DataStructures/RouteParameters.s

# target to generate assembly for a file
DataStructures/RouteParameters.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/RouteParameters.cpp.s
.PHONY : DataStructures/RouteParameters.cpp.s

DataStructures/SearchEngineData.o: DataStructures/SearchEngineData.cpp.o
.PHONY : DataStructures/SearchEngineData.o

# target to build an object file
DataStructures/SearchEngineData.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/SearchEngineData.cpp.o
.PHONY : DataStructures/SearchEngineData.cpp.o

DataStructures/SearchEngineData.i: DataStructures/SearchEngineData.cpp.i
.PHONY : DataStructures/SearchEngineData.i

# target to preprocess a source file
DataStructures/SearchEngineData.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/SearchEngineData.cpp.i
.PHONY : DataStructures/SearchEngineData.cpp.i

DataStructures/SearchEngineData.s: DataStructures/SearchEngineData.cpp.s
.PHONY : DataStructures/SearchEngineData.s

# target to generate assembly for a file
DataStructures/SearchEngineData.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/DataStructures/SearchEngineData.cpp.s
.PHONY : DataStructures/SearchEngineData.cpp.s

Descriptors/DescriptionFactory.o: Descriptors/DescriptionFactory.cpp.o
.PHONY : Descriptors/DescriptionFactory.o

# target to build an object file
Descriptors/DescriptionFactory.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Descriptors/DescriptionFactory.cpp.o
.PHONY : Descriptors/DescriptionFactory.cpp.o

Descriptors/DescriptionFactory.i: Descriptors/DescriptionFactory.cpp.i
.PHONY : Descriptors/DescriptionFactory.i

# target to preprocess a source file
Descriptors/DescriptionFactory.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Descriptors/DescriptionFactory.cpp.i
.PHONY : Descriptors/DescriptionFactory.cpp.i

Descriptors/DescriptionFactory.s: Descriptors/DescriptionFactory.cpp.s
.PHONY : Descriptors/DescriptionFactory.s

# target to generate assembly for a file
Descriptors/DescriptionFactory.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Descriptors/DescriptionFactory.cpp.s
.PHONY : Descriptors/DescriptionFactory.cpp.s

Extractor/BaseParser.o: Extractor/BaseParser.cpp.o
.PHONY : Extractor/BaseParser.o

# target to build an object file
Extractor/BaseParser.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/BaseParser.cpp.o
.PHONY : Extractor/BaseParser.cpp.o

Extractor/BaseParser.i: Extractor/BaseParser.cpp.i
.PHONY : Extractor/BaseParser.i

# target to preprocess a source file
Extractor/BaseParser.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/BaseParser.cpp.i
.PHONY : Extractor/BaseParser.cpp.i

Extractor/BaseParser.s: Extractor/BaseParser.cpp.s
.PHONY : Extractor/BaseParser.s

# target to generate assembly for a file
Extractor/BaseParser.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/BaseParser.cpp.s
.PHONY : Extractor/BaseParser.cpp.s

Extractor/ExtractionContainers.o: Extractor/ExtractionContainers.cpp.o
.PHONY : Extractor/ExtractionContainers.o

# target to build an object file
Extractor/ExtractionContainers.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractionContainers.cpp.o
.PHONY : Extractor/ExtractionContainers.cpp.o

Extractor/ExtractionContainers.i: Extractor/ExtractionContainers.cpp.i
.PHONY : Extractor/ExtractionContainers.i

# target to preprocess a source file
Extractor/ExtractionContainers.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractionContainers.cpp.i
.PHONY : Extractor/ExtractionContainers.cpp.i

Extractor/ExtractionContainers.s: Extractor/ExtractionContainers.cpp.s
.PHONY : Extractor/ExtractionContainers.s

# target to generate assembly for a file
Extractor/ExtractionContainers.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractionContainers.cpp.s
.PHONY : Extractor/ExtractionContainers.cpp.s

Extractor/ExtractorCallbacks.o: Extractor/ExtractorCallbacks.cpp.o
.PHONY : Extractor/ExtractorCallbacks.o

# target to build an object file
Extractor/ExtractorCallbacks.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractorCallbacks.cpp.o
.PHONY : Extractor/ExtractorCallbacks.cpp.o

Extractor/ExtractorCallbacks.i: Extractor/ExtractorCallbacks.cpp.i
.PHONY : Extractor/ExtractorCallbacks.i

# target to preprocess a source file
Extractor/ExtractorCallbacks.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractorCallbacks.cpp.i
.PHONY : Extractor/ExtractorCallbacks.cpp.i

Extractor/ExtractorCallbacks.s: Extractor/ExtractorCallbacks.cpp.s
.PHONY : Extractor/ExtractorCallbacks.s

# target to generate assembly for a file
Extractor/ExtractorCallbacks.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ExtractorCallbacks.cpp.s
.PHONY : Extractor/ExtractorCallbacks.cpp.s

Extractor/PBFParser.o: Extractor/PBFParser.cpp.o
.PHONY : Extractor/PBFParser.o

# target to build an object file
Extractor/PBFParser.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/PBFParser.cpp.o
.PHONY : Extractor/PBFParser.cpp.o

Extractor/PBFParser.i: Extractor/PBFParser.cpp.i
.PHONY : Extractor/PBFParser.i

# target to preprocess a source file
Extractor/PBFParser.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/PBFParser.cpp.i
.PHONY : Extractor/PBFParser.cpp.i

Extractor/PBFParser.s: Extractor/PBFParser.cpp.s
.PHONY : Extractor/PBFParser.s

# target to generate assembly for a file
Extractor/PBFParser.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/PBFParser.cpp.s
.PHONY : Extractor/PBFParser.cpp.s

Extractor/ScriptingEnvironment.o: Extractor/ScriptingEnvironment.cpp.o
.PHONY : Extractor/ScriptingEnvironment.o

# target to build an object file
Extractor/ScriptingEnvironment.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.o
.PHONY : Extractor/ScriptingEnvironment.cpp.o

Extractor/ScriptingEnvironment.i: Extractor/ScriptingEnvironment.cpp.i
.PHONY : Extractor/ScriptingEnvironment.i

# target to preprocess a source file
Extractor/ScriptingEnvironment.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.i
.PHONY : Extractor/ScriptingEnvironment.cpp.i

Extractor/ScriptingEnvironment.s: Extractor/ScriptingEnvironment.cpp.s
.PHONY : Extractor/ScriptingEnvironment.s

# target to generate assembly for a file
Extractor/ScriptingEnvironment.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.s
.PHONY : Extractor/ScriptingEnvironment.cpp.s

Extractor/XMLParser.o: Extractor/XMLParser.cpp.o
.PHONY : Extractor/XMLParser.o

# target to build an object file
Extractor/XMLParser.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/XMLParser.cpp.o
.PHONY : Extractor/XMLParser.cpp.o

Extractor/XMLParser.i: Extractor/XMLParser.cpp.i
.PHONY : Extractor/XMLParser.i

# target to preprocess a source file
Extractor/XMLParser.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/XMLParser.cpp.i
.PHONY : Extractor/XMLParser.cpp.i

Extractor/XMLParser.s: Extractor/XMLParser.cpp.s
.PHONY : Extractor/XMLParser.s

# target to generate assembly for a file
Extractor/XMLParser.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/Extractor/XMLParser.cpp.s
.PHONY : Extractor/XMLParser.cpp.s

Library/OSRM_impl.o: Library/OSRM_impl.cpp.o
.PHONY : Library/OSRM_impl.o

# target to build an object file
Library/OSRM_impl.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.o
.PHONY : Library/OSRM_impl.cpp.o

Library/OSRM_impl.i: Library/OSRM_impl.cpp.i
.PHONY : Library/OSRM_impl.i

# target to preprocess a source file
Library/OSRM_impl.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.i
.PHONY : Library/OSRM_impl.cpp.i

Library/OSRM_impl.s: Library/OSRM_impl.cpp.s
.PHONY : Library/OSRM_impl.s

# target to generate assembly for a file
Library/OSRM_impl.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.s
.PHONY : Library/OSRM_impl.cpp.s

Server/Connection.o: Server/Connection.cpp.o
.PHONY : Server/Connection.o

# target to build an object file
Server/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/Connection.cpp.o
.PHONY : Server/Connection.cpp.o

Server/Connection.i: Server/Connection.cpp.i
.PHONY : Server/Connection.i

# target to preprocess a source file
Server/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/Connection.cpp.i
.PHONY : Server/Connection.cpp.i

Server/Connection.s: Server/Connection.cpp.s
.PHONY : Server/Connection.s

# target to generate assembly for a file
Server/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/Connection.cpp.s
.PHONY : Server/Connection.cpp.s

Server/Http/Reply.o: Server/Http/Reply.cpp.o
.PHONY : Server/Http/Reply.o

# target to build an object file
Server/Http/Reply.cpp.o:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Server/Http/Reply.cpp.o
.PHONY : Server/Http/Reply.cpp.o

Server/Http/Reply.i: Server/Http/Reply.cpp.i
.PHONY : Server/Http/Reply.i

# target to preprocess a source file
Server/Http/Reply.cpp.i:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Server/Http/Reply.cpp.i
.PHONY : Server/Http/Reply.cpp.i

Server/Http/Reply.s: Server/Http/Reply.cpp.s
.PHONY : Server/Http/Reply.s

# target to generate assembly for a file
Server/Http/Reply.cpp.s:
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Server/Http/Reply.cpp.s
.PHONY : Server/Http/Reply.cpp.s

Server/RequestHandler.o: Server/RequestHandler.cpp.o
.PHONY : Server/RequestHandler.o

# target to build an object file
Server/RequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestHandler.cpp.o
.PHONY : Server/RequestHandler.cpp.o

Server/RequestHandler.i: Server/RequestHandler.cpp.i
.PHONY : Server/RequestHandler.i

# target to preprocess a source file
Server/RequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestHandler.cpp.i
.PHONY : Server/RequestHandler.cpp.i

Server/RequestHandler.s: Server/RequestHandler.cpp.s
.PHONY : Server/RequestHandler.s

# target to generate assembly for a file
Server/RequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestHandler.cpp.s
.PHONY : Server/RequestHandler.cpp.s

Server/RequestParser.o: Server/RequestParser.cpp.o
.PHONY : Server/RequestParser.o

# target to build an object file
Server/RequestParser.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestParser.cpp.o
.PHONY : Server/RequestParser.cpp.o

Server/RequestParser.i: Server/RequestParser.cpp.i
.PHONY : Server/RequestParser.i

# target to preprocess a source file
Server/RequestParser.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestParser.cpp.i
.PHONY : Server/RequestParser.cpp.i

Server/RequestParser.s: Server/RequestParser.cpp.s
.PHONY : Server/RequestParser.s

# target to generate assembly for a file
Server/RequestParser.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/Server/RequestParser.cpp.s
.PHONY : Server/RequestParser.cpp.s

Util/GitDescription.o: Util/GitDescription.cpp.o
.PHONY : Util/GitDescription.o

# target to build an object file
Util/GitDescription.cpp.o:
	$(MAKE) -f CMakeFiles/GITDESCRIPTION.dir/build.make CMakeFiles/GITDESCRIPTION.dir/Util/GitDescription.cpp.o
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Util/GitDescription.cpp.o
.PHONY : Util/GitDescription.cpp.o

Util/GitDescription.i: Util/GitDescription.cpp.i
.PHONY : Util/GitDescription.i

# target to preprocess a source file
Util/GitDescription.cpp.i:
	$(MAKE) -f CMakeFiles/GITDESCRIPTION.dir/build.make CMakeFiles/GITDESCRIPTION.dir/Util/GitDescription.cpp.i
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Util/GitDescription.cpp.i
.PHONY : Util/GitDescription.cpp.i

Util/GitDescription.s: Util/GitDescription.cpp.s
.PHONY : Util/GitDescription.s

# target to generate assembly for a file
Util/GitDescription.cpp.s:
	$(MAKE) -f CMakeFiles/GITDESCRIPTION.dir/build.make CMakeFiles/GITDESCRIPTION.dir/Util/GitDescription.cpp.s
	$(MAKE) -f CMakeFiles/OSRM.dir/build.make CMakeFiles/OSRM.dir/Util/GitDescription.cpp.s
.PHONY : Util/GitDescription.cpp.s

Util/UUID.o: Util/UUID.cpp.o
.PHONY : Util/UUID.o

# target to build an object file
Util/UUID.cpp.o:
	$(MAKE) -f CMakeFiles/UUID.dir/build.make CMakeFiles/UUID.dir/Util/UUID.cpp.o
.PHONY : Util/UUID.cpp.o

Util/UUID.i: Util/UUID.cpp.i
.PHONY : Util/UUID.i

# target to preprocess a source file
Util/UUID.cpp.i:
	$(MAKE) -f CMakeFiles/UUID.dir/build.make CMakeFiles/UUID.dir/Util/UUID.cpp.i
.PHONY : Util/UUID.cpp.i

Util/UUID.s: Util/UUID.cpp.s
.PHONY : Util/UUID.s

# target to generate assembly for a file
Util/UUID.cpp.s:
	$(MAKE) -f CMakeFiles/UUID.dir/build.make CMakeFiles/UUID.dir/Util/UUID.cpp.s
.PHONY : Util/UUID.cpp.s

datastore.o: datastore.cpp.o
.PHONY : datastore.o

# target to build an object file
datastore.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-datastore.dir/build.make CMakeFiles/osrm-datastore.dir/datastore.cpp.o
.PHONY : datastore.cpp.o

datastore.i: datastore.cpp.i
.PHONY : datastore.i

# target to preprocess a source file
datastore.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-datastore.dir/build.make CMakeFiles/osrm-datastore.dir/datastore.cpp.i
.PHONY : datastore.cpp.i

datastore.s: datastore.cpp.s
.PHONY : datastore.s

# target to generate assembly for a file
datastore.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-datastore.dir/build.make CMakeFiles/osrm-datastore.dir/datastore.cpp.s
.PHONY : datastore.cpp.s

extractor.o: extractor.cpp.o
.PHONY : extractor.o

# target to build an object file
extractor.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/extractor.cpp.o
.PHONY : extractor.cpp.o

extractor.i: extractor.cpp.i
.PHONY : extractor.i

# target to preprocess a source file
extractor.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/extractor.cpp.i
.PHONY : extractor.cpp.i

extractor.s: extractor.cpp.s
.PHONY : extractor.s

# target to generate assembly for a file
extractor.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-extract.dir/build.make CMakeFiles/osrm-extract.dir/extractor.cpp.s
.PHONY : extractor.cpp.s

prepare.o: prepare.cpp.o
.PHONY : prepare.o

# target to build an object file
prepare.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/prepare.cpp.o
.PHONY : prepare.cpp.o

prepare.i: prepare.cpp.i
.PHONY : prepare.i

# target to preprocess a source file
prepare.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/prepare.cpp.i
.PHONY : prepare.cpp.i

prepare.s: prepare.cpp.s
.PHONY : prepare.s

# target to generate assembly for a file
prepare.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-prepare.dir/build.make CMakeFiles/osrm-prepare.dir/prepare.cpp.s
.PHONY : prepare.cpp.s

routed.o: routed.cpp.o
.PHONY : routed.o

# target to build an object file
routed.cpp.o:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/routed.cpp.o
.PHONY : routed.cpp.o

routed.i: routed.cpp.i
.PHONY : routed.i

# target to preprocess a source file
routed.cpp.i:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/routed.cpp.i
.PHONY : routed.cpp.i

routed.s: routed.cpp.s
.PHONY : routed.s

# target to generate assembly for a file
routed.cpp.s:
	$(MAKE) -f CMakeFiles/osrm-routed.dir/build.make CMakeFiles/osrm-routed.dir/routed.cpp.s
.PHONY : routed.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... COORDLIB"
	@echo "... GITDESCRIPTION"
	@echo "... OSRM"
	@echo "... UUID"
	@echo "... UUIDConfigure"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... osrm-datastore"
	@echo "... osrm-extract"
	@echo "... osrm-prepare"
	@echo "... osrm-routed"
	@echo "... rebuild_cache"
	@echo "... Algorithms/DouglasPeucker.o"
	@echo "... Algorithms/DouglasPeucker.i"
	@echo "... Algorithms/DouglasPeucker.s"
	@echo "... Algorithms/PolylineCompressor.o"
	@echo "... Algorithms/PolylineCompressor.i"
	@echo "... Algorithms/PolylineCompressor.s"
	@echo "... Contractor/EdgeBasedGraphFactory.o"
	@echo "... Contractor/EdgeBasedGraphFactory.i"
	@echo "... Contractor/EdgeBasedGraphFactory.s"
	@echo "... Contractor/GeometryCompressor.o"
	@echo "... Contractor/GeometryCompressor.i"
	@echo "... Contractor/GeometryCompressor.s"
	@echo "... Contractor/TemporaryStorage.o"
	@echo "... Contractor/TemporaryStorage.i"
	@echo "... Contractor/TemporaryStorage.s"
	@echo "... DataStructures/Coordinate.o"
	@echo "... DataStructures/Coordinate.i"
	@echo "... DataStructures/Coordinate.s"
	@echo "... DataStructures/HilbertValue.o"
	@echo "... DataStructures/HilbertValue.i"
	@echo "... DataStructures/HilbertValue.s"
	@echo "... DataStructures/RestrictionMap.o"
	@echo "... DataStructures/RestrictionMap.i"
	@echo "... DataStructures/RestrictionMap.s"
	@echo "... DataStructures/RouteParameters.o"
	@echo "... DataStructures/RouteParameters.i"
	@echo "... DataStructures/RouteParameters.s"
	@echo "... DataStructures/SearchEngineData.o"
	@echo "... DataStructures/SearchEngineData.i"
	@echo "... DataStructures/SearchEngineData.s"
	@echo "... Descriptors/DescriptionFactory.o"
	@echo "... Descriptors/DescriptionFactory.i"
	@echo "... Descriptors/DescriptionFactory.s"
	@echo "... Extractor/BaseParser.o"
	@echo "... Extractor/BaseParser.i"
	@echo "... Extractor/BaseParser.s"
	@echo "... Extractor/ExtractionContainers.o"
	@echo "... Extractor/ExtractionContainers.i"
	@echo "... Extractor/ExtractionContainers.s"
	@echo "... Extractor/ExtractorCallbacks.o"
	@echo "... Extractor/ExtractorCallbacks.i"
	@echo "... Extractor/ExtractorCallbacks.s"
	@echo "... Extractor/PBFParser.o"
	@echo "... Extractor/PBFParser.i"
	@echo "... Extractor/PBFParser.s"
	@echo "... Extractor/ScriptingEnvironment.o"
	@echo "... Extractor/ScriptingEnvironment.i"
	@echo "... Extractor/ScriptingEnvironment.s"
	@echo "... Extractor/XMLParser.o"
	@echo "... Extractor/XMLParser.i"
	@echo "... Extractor/XMLParser.s"
	@echo "... Library/OSRM_impl.o"
	@echo "... Library/OSRM_impl.i"
	@echo "... Library/OSRM_impl.s"
	@echo "... Server/Connection.o"
	@echo "... Server/Connection.i"
	@echo "... Server/Connection.s"
	@echo "... Server/Http/Reply.o"
	@echo "... Server/Http/Reply.i"
	@echo "... Server/Http/Reply.s"
	@echo "... Server/RequestHandler.o"
	@echo "... Server/RequestHandler.i"
	@echo "... Server/RequestHandler.s"
	@echo "... Server/RequestParser.o"
	@echo "... Server/RequestParser.i"
	@echo "... Server/RequestParser.s"
	@echo "... Util/GitDescription.o"
	@echo "... Util/GitDescription.i"
	@echo "... Util/GitDescription.s"
	@echo "... Util/UUID.o"
	@echo "... Util/UUID.i"
	@echo "... Util/UUID.s"
	@echo "... datastore.o"
	@echo "... datastore.i"
	@echo "... datastore.s"
	@echo "... extractor.o"
	@echo "... extractor.i"
	@echo "... extractor.s"
	@echo "... prepare.o"
	@echo "... prepare.i"
	@echo "... prepare.s"
	@echo "... routed.o"
	@echo "... routed.i"
	@echo "... routed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

